const component = {
    loginwelcome:"Welcome Back !",
    loginsing:"Sing in to continue to Bunatetu Admin",
    email:"Email-id",
    password:"password",
    Sign:"Sign in",

    admin:"Admin",
    Passwordchange:"Change Password",
    logout:"Logout",
    Dashboard:"Dashboard",
    user:"User",
    dashuser:"All user",
    dashAdduser:"Add user",
    product:"Product",
    dropaddpro:"Add Product",
    dropAllpro:"All Product",
    category:"category",
    dashcategory:"All Category",
    dashorder:"Add to cart",
    dashpikuporder:"Pick up order",
    dashdelivery:"delivery Order",
    order:"order",
    noti:"Notification",

    Dash:"DASHBOARD",
    welcomedash:"Welcome to Dashboard",
    totalcomorder:"Total Completed Order",
    completedorder:"2",
    todayorder:"Today's Order",
    todaysorder:"0",
    users:"Users",
    totaluser:"30",
    dascategory:"Category",
    totalcty:"7",
    dasproduct:"Product",
    dastotalproduct:"54",
}
export default component